export const data = [
    { id: 1, 
      type: 'Google', 
      image: './sicon/Gmail.png', 
      hadLine: 'Gmail', 
      description: 'Send Gmail messages from your own account directly', 
    },
    { id: 2, 
      type: 'Google', 
      image: './sicon/Caledar.png', 
      hadLine: 'Google Caledar', 
      description: 'Create Google events using data from your Workspace', 
    },
    { id: 3, 
      type: 'Google', 
      image: './sicon/GMeet.png', 
      hadLine: 'Google Meet', 
      description: 'Create Google events using data from your Workspace', 
    },
    { id: 4, 
      type: 'Microsoft', 
      image: './sicon/Outlook.png', 
      hadLine: 'Microsoft Outlook', 
      description: 'Send email from your Outlook account directly', 
    },
    { id: 5, 
      type: 'Microsoft', 
      image: './sicon/OCalendar.png', 
      hadLine: 'Outlook Calendar', 
      description: 'Send Gmail messages from your own account directly', 
    },
    { id: 6, 
      type: 'Microsoft', 
      image: './sicon/Team.png', 
      hadLine: 'Microsoft Team', 
      description: 'Send email from your Outlook account directly', 
    },
    { id: 7, 
      type: 'Whatsapp', 
      image: './sicon/Whatsapp.png', 
      hadLine: 'Whatsapp', 
      description: 'Get notified on Whatsapp when something is going on and Send SMS', 
    },
    { id: 8, 
      type: 'Slack', 
      image: './sicon/Slack.png', 
      hadLine: 'Slack', 
      description: 'Get notified on Whatsapp when something is going on and Send SMS', 
    },
    { id: 9, 
      type: 'Skype', 
      image: './sicon/Skype.png', 
      hadLine: 'Skype', 
      description: 'Get notified on Whatsapp when something is going on and Send SMS', 
    },
    { id: 10, 
      type: 'LinkedIn', 
      image: './sicon/LinkedIn.png', 
      hadLine: 'LinkedIn', 
      description: 'Get notified on Whatsapp when something is going on and Send SMS', 
    },
    { id: 11, 
      type: 'Zoom', 
      image: './sicon/zoom.png', 
      hadLine: 'Zoom', 
      description: 'Get notified on Whatsapp when something is going on and Send SMS', 
    },
    { id: 12, 
      type: 'Calendly', 
      image: './sicon/Calendlyy.png', 
      hadLine: 'Calendly', 
      description: 'Get notified on Whatsapp when something is going on and Send SMS', 
    },
    { id: 13, 
      type: 'Dialer', 
      image: './sicon/Polygon.png', 
      hadLine: 'Dialer', 
      description: 'Get notified on Whatsapp when something is going on and Send SMS', 
    },
   
];
