export const data = [
  {
      image: './sicon/gmail.png',
      url: '/pipeline',
      name: 'Google GMail',
      hadLine1: 'Google GMail',
      hadLine2: 'Quikit',
      description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
  },
  {
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Google Caledar',
    hadLine1: 'Google Caledar',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Google GMeet',
    hadLine1: 'Google GMeet',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Microsoft Outlook',
    hadLine1: 'Microsoft Outlook',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Outlook Calendar',
    hadLine1: 'Outlook Calendar',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Microsoft Team',
    hadLine1: 'Microsoft Team',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Whatsapp',
    hadLine1: 'Whatsapp',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Calendly',
    hadLine1: 'Calendly',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Slack',
    hadLine1: 'Slack',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Calendly',
    hadLine1: 'Calendly',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'x',
    hadLine1: 'x',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Skype',
    hadLine1: 'Skype',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Instagram',
    hadLine1: 'Instagram',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'LinkedIn',
    hadLine1: 'LinkedIn',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Facebook',
    hadLine1: 'Facebook',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Zoom',
    hadLine1: 'Zoom',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Calendly',
    hadLine1: 'Calendly',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Youtube',
    hadLine1: 'Youtube',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},
{
    image: 'path/to/microsoft-outlook-image.png',
    url: '/pipeline',
    name: 'Twilio',
    hadLine1: 'Twilio',
    hadLine2: 'Quikit',
    description: 'Connecting allows our products to interact with Microsoft Outlook 365 data on your behalf. This may include read, write, modify and delete data, depending on your Microsoft Outlook 365 permissions.',
},


];

